### ISSUE TITLE
New-HVPool -datastores

### ISSUE THREAD

**Issue by maniaX1** [vmware/PowerCLI-Example-Scripts#138]
Hey guys, I have been trying all day to figure out how to specify more than one Datastore in New-HVPool cmdlet.
I have no problem with one..... New-HVPool -Datastores "SEN-Example"
But How I can achieve command with two datastores? I tried:
-Datastores "SEN1,SEN2"
-Datastores "SEN1[0],SEN2[1]"
....and many others combinations. I haven't found any explanation in Detailed help so I don't know where to look more.

Can you help me with this?
Thanks!

**Comment by rpstester** [comment]
Are you getting an error like: 

> Method invocation failed because [VMware.Hv.DesktopVirtualCenterDatastoreSettings] does not contain a method named 'op_Addition'.

I think that there is a bug in the internal function function Get-HVDatastore (on vmware.hv.helper.psm1)
It makes it a $null object on line 5042, and later, it tries to add another object to it, but it's not an array, so it cannot add an item. 
```PowerShell
 $Datastores = $null
...
 foreach ($ds in $datastoresSelected) {
    $myDatastores = New-Object VMware.Hv.DesktopVirtualCenterDatastoreSettings
    $myDatastores.Datastore = $ds
    $mydatastores.StorageOvercommit = $DsStorageOvercommit[$StorageOvercommitCnt]
    $Datastores += $myDatastores #here is the problem line
    $StorageOvercommitCnt++
  }

```

Suggestion: It may be as simple as setting the variable to an empty array instead of a $null.

**Comment by mtelvers** [comment]
@rpstester I tried `$Datastores = @()` earlier but there's something else wrong as well because it errors later as follows

`Exception calling "Desktop_Create" with "2" argument(s): "ExceptionType : VMware.Hv.InvalidArgument
ErrorMessage : Invalid value for member
ParameterName : automatedDesktopSpec.virtualCenterProvisioningSettings.virtualCenterStorageSettings.datastores[1].storageOvercommit"
At VMware.Hv.Helper\VMware.HV.Helper.psm1:4719 char:7
+       $id = $desktop_helper.Desktop_create($services,$desktopSpecObj)
+       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : VimException`

I'll try to fix it

**Comment by mtelvers** [comment]
Please try PR #139.  The syntax on the command line should be `-Datastores SEN1,SEN2`.  If your datastore name has spaces then you'd write `-Datastores "SEN 1","SEN 2"`

**Comment by maniaX1** [comment]
**Perfect -Datastores SAN1,SAN2 works!** But I discovered that parameter -PersistentDiskStorageOvercommit "Conservative" doesn't work. There is still "unbounded" value which is I suppose the default.

**Comment by mtelvers** [comment]
@maniaX1 Are you using persistent storage?  Are specifying `-UseSeparateDatastoresPersistentAndOSDisks $true` ?

If you are just looking to get the usage policy the datastores set with `-Datastores ds1,ds2` then you should use `-storageOvercommit policy1,policy2`.

If you are using persistent storage you need to specify both `-PersistentDiskStorageOvercommit` and `-PersistentDiskDatastores` however, this doesn't seem to work at all.  The code crashes out before creating the pool.  I'll try to fix it.

**Comment by mtelvers** [comment]
I've added a second part to PR #139 to address the specific issue when persistent disk storage is specified.  You can now successfully have something like this

`New-HVPool ... -UseSeparateDatastoresPersistentAndOSDisks $true -PersistentDiskDatastores DS1,DS2 -PersistentDiskStorageOvercommit Policy1,Policy2`

**Comment by maniaX1** [comment]
I tested again and commit below helped me with parameter -StorageOvercommit CONSERVATIVE,CONSERVATIVE

COMMIT:
Fix to New-HVPool when persistent datastores are specified
Function Get_Datastore should read Get-HVDatastore

THANK YOU!

**Comment by kamennikolov** [comment]
Fixed by https://github.com/vmware/PowerCLI-Example-Scripts/pull/139
