### ISSUE TITLE
Horizon view Replica Server

### ISSUE THREAD

**Issue by SundaramBabu** [vmware/PowerCLI-Example-Scripts#220]
Hi

Is it possible to detect whether the given connection server is standard or replica server?

**Comment by mtelvers** [comment]
It's only a replica during installation meaning that it joins an existing deployment rather than creates a new one.  It's LDAP replication in the same way an Active Directory domain.  You can find out which server owns the various roles and transfer them using `DSMGMT.EXE` which is occasionally necessary when a role master server is removed.
